joezuntz/cosmosis

- setup.py
We need to tell setup.py that if is installing with the `-e` flag then it should run the Makefile and build the main cosmosis core.
> Enable developer installs

- cosmosis/output/cosmomc_output.py
- cosmosis/test/test_text_output.py
Changes the cosmomc output format to put the posterior in the second column instead of the last.
Addresses #16
> Fix CosmoMC output format

- .github/workflows/ci.yml
- cosmosis/configure.py
The current configure program, `cosmosis-configure`, can fail on some bash versions because it is sent a multi-line string from `cosmosis/configure.py`, which does not work correctly - the later lines don't see the changes made in the first line.
This puts them all in a single statement with semi-colon separators.
> Change to bash-friendly configure program

- cosmosis/samplers/zeus/zeus_sampler.py
This PR fixes a subtle bug in the way zeus is run. So far, when `patience` is set to a value larger than `nsteps`, the sampler cannot run more iterations than `patience` at a time, by design. Therefore, tuning might never end. This is fixed by subtracting the number of past iterations from patience after the sampler is run.
> Enable zeus patience for small nsteps

- cosmosis/runtime/parameter.py
- cosmosis/test/test_parameters.py
Previously the -v flag could only modify existing parameters. This allows it to add new ones as well.
> Allow new parameters to be added using the -v flag

- cosmosis/config/compilers.mk
This fixes OpenMP flags not being set correctly.
> Fix OpenMP flags in compilers.mk

- cosmosis/main.py
- cosmosis/test/test_pipeline.py
- cosmosis/test/test_utils.py
- cosmosis/utils.py
- setup.py
These can crash perlmutter jobs.
> Add a way to avoid launching subprocesses

- cosmosis/datablock/c_datablock.cc
- cosmosis/test/test_block.py
Currently if you go through the python layer and `put` a 1D array of one type and then `get` the same array but with the wrong type then you get a c++ crash instead of a python exception. 
This fixes that by adding the necessary try/catch in each of the relevant functions.
> Fix hard crash when using wrong array types with put/get

- cosmosis/main.py
- cosmosis/postprocessing/postprocess.py
- cosmosis/postprocessing/statistics.py
- cosmosis/samplers/__init__.py
- cosmosis/samplers/multinest/multinest_sampler.py
- cosmosis/samplers/nautilus/nautilus_sampler.py
- cosmosis/samplers/nautilus/sampler.yaml
- cosmosis/samplers/polychord/polychord_sampler.py
- cosmosis/samplers/sampler.py
- cosmosis/test/test_samplers.py
- requirements.txt
- setup.py
This PR adds the nautilus sampler (https://nautilus-sampler.readthedocs.io/). I could need some help ensuring that everything works as expected.
* blobs: Nautilus supports blobs. The interface is very similar to emcee's. But I still need to figure out how to give those results back to CosmoSIS.
* MPI: Nautilus supports MPI parallelization via schwimmbad or any pool with a `map` method, just like emcee and dynesty. Seeing how dynesty and emcee are interfaced, MPI parallelization may already work. But that needs to be tested.
* tests: No unit tests have been implemented yet.
> Implement nautilus sampler interface

- cosmosis/samplers/list/list_sampler.py
Hi,
I've encountered a bug in the list sampler when I asked for vector quantities as additional outputs. Basically, the sampler didn't set up the correct number of extra columns in the output file.
This pull request fixes this issue by reusing some pieces of code from the output_names function defined in pipeline.py.
Best,
Benjamin
> Bugfix for list sampler with vector quantities as extra output

- cosmosis/test/test_samplers.py
This is mainly to ensure that the right version is packaged in conda.
> Add a test of additional nautilus options

- cosmosis/samplers/dynesty/dynesty_sampler.py
The newer version of dynesty can return blobs like emcee etc. So we can have derived params now. We use that to save the prior too.
> Update dynesty to save blobs and prior

- cosmosis/campaign.py
- cosmosis/runtime/config.py
- cosmosis/test/campaign.yml
- cosmosis/test/example.ini
- cosmosis/test/test_campaign.py
> Defer expanding environment variables in parent campaign runs so children can override

- cosmosis/samplers/nautilus/nautilus_sampler.py
- cosmosis/samplers/nautilus/sampler.yaml
- requirements.txt
- setup.py
This PR should update the nautilus sampler integration to version 1.0. Currently, `cosmosis` actually only supports nautilus version 0.6. What was the reason for not supporting 0.7? By the way, the updates in 0.7 and 1.0 are fairly minor. Still, it would be good to update cosmosis to nautilus 1.0.
> Update nautilus integration to 1.0

- cosmosis/__init__.py
- cosmosis/main.py
- cosmosis/samplers/list/list_sampler.py
- cosmosis/samplers/minuit/minuit_sampler.py
- cosmosis/samplers/sampler.py
- cosmosis/test/test_samplers.py
Addresses issue #122 
Also I spotted a couple of other issues along the way that this fixes:
- The successful run count was being reported incorrectly
- The Sampler.get_sampler function was not working.
- Added the output classes to be imported into main namespace
> Fix thinning and burning in list sampler

- cosmosis/output/text_output.py
- cosmosis/postprocessing/v2/__init__.py
- cosmosis/postprocessing/v2/chains.py
I plan to replace the post-processing system with something less confusing. This is the first step in that.
Also fixes a bug when emcee or MH chains are resumed.
> Add preliminary classes for version 2 of the postprocessing system

- cosmosis/main.py
- cosmosis/test/test_parameters.py
Addresses problem where values overridden on the command line with the `-v` flag are not recorded correctly in the output file.
> Propagate command line changes to the values file into output headers

- cosmosis/samplers/poco/poco_sampler.py
- cosmosis/samplers/poco/sampler.yaml
Added support for controlling the number of MCMC steps per iteration
> n_steps control for pocoMC

- cosmosis/samplers/poco/poco_sampler.py
Addresses issue #136 
Currently the prior object cosmosis gives to PocoMC includes a reference to the complete pipeline object. If this fails to pickle then the PocoMC save state process fails too.
This changes things to use a global pipeline variable instead, which already existed because the sampler MPI needed it.
> Change pocomc.Prior object to use a global Pipeline variabkle

- cosmosis/samplers/apriori/apriori_sampler.py
- cosmosis/samplers/dynesty/dynesty_sampler.py
- cosmosis/samplers/emcee/emcee_sampler.py
- cosmosis/samplers/grid/grid_sampler.py
- cosmosis/samplers/gridmax/gridmax_sampler.py
- cosmosis/samplers/hints.py
- cosmosis/samplers/importance/importance_sampler.py
- cosmosis/samplers/kombine/kombine_sampler.py
- cosmosis/samplers/list/list_sampler.py
- cosmosis/samplers/maxlike/maxlike_sampler.py
- cosmosis/samplers/metropolis/metropolis_sampler.py
- cosmosis/samplers/minuit/minuit_sampler.py
- cosmosis/samplers/multinest/multinest_sampler.py
- cosmosis/samplers/nautilus/nautilus_sampler.py
- cosmosis/samplers/pmaxlike/pmaxlike_sampler.py
- cosmosis/samplers/pmc/pmc_sampler.py
- cosmosis/samplers/poco/poco_sampler.py
- cosmosis/samplers/polychord/polychord_sampler.py
- cosmosis/samplers/pymc/pymc_sampler.py
- cosmosis/samplers/snake/snake_sampler.py
- cosmosis/samplers/star/star_sampler.py
- cosmosis/samplers/zeus/zeus_sampler.py
- cosmosis/test/test_samplers.py
Currently only the max-like style samplers save their best-fitting sample as a hint to be used by subsequent samplers, when using sampler chaining mode. This updates the other samplers to do the same.
> Have the rest of the samplers save their best-fit as a hint

- cosmosis/postprocessing/plots.py
I found this to be useful for testing sampling runs with maxlike + fisher.
> include truth values on Fisher matrix plots

- cosmosis/samplers/nautilus/nautilus_sampler.py
This PR fixes an error when saving the output from the Nautilus sampler. It checks whether the `blob` variable is an array of floats or tuples and then refactors them appropriately for saving/processing. This will close #162.
> Fix error in NautilusSampler when saving outputs

- cosmosis/samplers/maxlike/maxlike_sampler.py
- cosmosis/test/test_samplers.py
Saves the complete datablock for the best-fit overall model
> Add output_block option to maxlike sampler

- cosmosis/campaign.py
This is a small change to support yaml merge keys based on the same gist discussion referenced in the code. This should support constructions such as:
```yaml
runs:
- name: run1
...
submission: &submit
template: ...
time: 12:00:00
- name: run2
....
submission:
<<: *submit
time: 16:00:00
```
> handle yaml merge keys

- cosmosis/samplers/metropolis/metropolis_sampler.py
Thanks to Nigel Hambly for reporting a symptom of this issue - a metropolis object being saved was storing a reference to a cosmosis datablock. When this was checkpointed a very large amount of data could be saved, and worse it was converted to text format so became extremely large and slow. 
This is a quick and lazy way of avoiding that issue by removing the block.
> Avoid serializing the current sample data block in metropolis checkpoints
